# Dockerfile.bridge
FROM python:3.11-slim

WORKDIR /app

COPY mock_server /app/mock_server
COPY requirements.txt /app

RUN pip install --no-cache-dir -r /app/requirements.txt

CMD ["python", "mock_server/kafka_ws_bridge.py"]
